COMMIT_MESSAGE_ERRORS

diff --git a/.github/workflows/extended_regexp_invert_grep.yml b/.github/workflows/extended_regexp_invert_grep.yml
--- a/.github/workflows/extended_regexp_invert_grep.yml
+++ b/.github/workflows/extended_regexp_invert_grep.yml
@@ -23,15 +23,12 @@ jobs:
           set -o noclobber # don't overwrite exists files via >
           set -o pipefail  # fails if pipes (|) fails
           # set -o xtrace  # debug
-          readarray -t LIST_MESSAGE_COMMITS < <(git log ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --pretty=format:%s)
-          for MESSAGE_COMMITS in "${LIST_MESSAGE_COMMITS[@]}"
-          do
-            if ! [[ ${MESSAGE_COMMITS} =~ ${COMMIT_MESSAGE_REGEXP} ]]; then
-              echo "Invalid message commit:"
-              git log ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --pretty=format:%s --grep="${COMMIT_MESSAGE_REGEXP}" --extended-regexp --invert-grep
-              exit 1
-            fi
-          done
+          COMMIT_MESSAGE_ERRORS=$(git log ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --pretty=format:%s  --grep="${COMMIT_MESSAGE_REGEXP}" --extended-regexp --invert-grep)
+          if [[ "$COMMIT_MESSAGE_ERRORS" ]]; then
+            echo "Format of commit messages is incorrect, rexep : ${COMMIT_MESSAGE_REGEXP}"
+            echo "${COMMIT_MESSAGE_ERRORS}"
+            exit 1
+          fi
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
